name: GitHub Actions Test
run-name: ${{ github.actor }} is testing Positivarium front-end application via GitHub Actions.
on: [push]
jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: Test code
        run: |
          npm install
          npm test

      - name: Deploy to Vercel Preview
        if: success() && github.ref != 'refs/heads/main'
        run: npx vercel --project ${{ secrets.VERCEL_PROJECT_ID }} --org ${{ secrets.VERCEL_ORG_ID }} --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy to Vercel Production
        if: success() && github.ref == 'refs/heads/main'
        run: npx vercel --project ${{ secrets.VERCEL_PROJECT_ID }} --org ${{ secrets.VERCEL_ORG_ID }} --prod --token=${{ secrets.VERCEL_TOKEN }} --yes

      - run: echo "This job's status is ${{ job.status }}."
